// <auto-generated />
namespace FinancialAccounting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingCompanyAndBranches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingCompanyAndBranches));
        
        string IMigrationMetadata.Id
        {
            get { return "202202091236441_addingCompanyAndBranches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
